CREATE TABLE IF NOT EXISTS MPA (
	id              int             NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name            varchar         NOT NULL
 	);

CREATE TABLE IF NOT EXISTS FILMS (
	id              int             NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	name            varchar,
	description     varchar(200)    NOT NULL,
 	release_date    date            NOT NULL,
 	duration        int             NOT NULL,
 	mpa             int             NOT NULL references MPA(id)
 	);
 
 
 CREATE TABLE IF NOT EXISTS GENRE (
	genre_id        int             NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	genre           varchar         NOT NULL
 	);
 	
 CREATE TABLE IF NOT EXISTS FILM_GENRE (
	film_id         int             NOT NULL references FILMS(id) ON DELETE CASCADE,
	genre_id        int             NOT NULL references GENRE(genre_id) ON DELETE CASCADE
 	);
 	
 CREATE TABLE IF NOT EXISTS USERS (
 	id              int             NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 	email           varchar         NOT NULL,
 	login           varchar         NOT NULL,
 	name            varchar         NOT NULL,
 	birthday        date            NOT NULL
 	);
 
 CREATE TABLE IF NOT EXISTS USER_FRIEND (
 	user_id         int             NOT NULL REFERENCES USERS(id) ON DELETE CASCADE,
 	friend_id       int             NOT NULL REFERENCES USERS(id) ON DELETE CASCADE,
 	CONSTRAINT films_pk PRIMARY KEY (user_id, friend_id)
 	);
 

 CREATE TABLE IF NOT EXISTS USER_FILM (
 	user_id         int             NOT NULL REFERENCES USERS(id) ON DELETE CASCADE,
 	film_id         int             NOT NULL REFERENCES FILMS(id) ON DELETE CASCADE,
 	CONSTRAINT user_film_pk PRIMARY KEY (user_id, film_id)
 	);